config/routes.rb
Rails.application.routes.draw do
  resources :todolists
  get 'top/index'

  root "top#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todolist.rb
class Todolist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy]

  # GET /todolists
  # GET /todolists.json
  def index
    @todolists = Todolist.all
  end

  # GET /todolists/1
  # GET /todolists/1.json
  def show
  end

  # GET /todolists/new
  def new
    @todolist = Todolist.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists
  # POST /todolists.json
  def create
    @todolist = Todolist.new(todolist_params)

    respond_to do |format|
      if @todolist.save
        format.html { redirect_to @todolist, notice: '新しいTODOを登録しました。頑張ってください。' }
        format.json { render :show, status: :created, location: @todolist }
      else
        format.html { render :new }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todolists/1
  # PATCH/PUT /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to @todolist, notice: 'TODO内容を更新しました。' }
        format.json { render :show, status: :ok, location: @todolist }
      else
        format.html { render :edit }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1
  # DELETE /todolists/1.json
  def destroy
    @todolist.destroy
    respond_to do |format|
      format.html { redirect_to todolists_url, notice: 'お疲れ様でした。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = Todolist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todolist_params
      params.require(:todolist).permit(:today, :todo, :memo, :deadline)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    @todolists = Todolist.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo010</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/_form.html.erb
<%= form_with(model: todolist, local: true) do |form| %>
  <% if todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
      <% todolist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :登録日 %>
    <%= form.date_select :today %>
  </div>

  <div class="field">
    <%= form.label :TODO %>
    <%= form.text_field :todo %>
  </div>

  <div class="field">
    <%= form.label :メモ %>
    <%= form.text_field :memo %>
  </div>

  <div class="field">
    <%= form.label :〆切 %>
    <%= form.date_select :deadline %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todolists/edit.html.erb
<h1>Editing Todolist</h1>

<%= render 'form', todolist: @todolist %>

<%= link_to 'Show', @todolist %> |
<%= link_to 'Back', todolists_path %>

app/views/todolists/index.html.erb
<p id="notice"><%= notice %></p>

<!DOCTYPE html>
<html lang='ja'>
<head>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width'>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.0/css/bootstrap.min.css"></link>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.10/angular.min.js"></script>

<link rel="stylesheet" type="text/css" href="1026.css">

</head>
<body>

<h1>TODOリスト一覧</h1>

<br>

<CENTER>

<table>
  <thead>
    <tr>
      <th>登録日</th>
      <th>TODO</th>
      <th>メモ</th>
      <th>〆切</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todolists.each do |todolist| %>
      <tr>
        <td><%= todolist.today %></td>
        <td><%= todolist.todo %></td>
        <td><%= todolist.memo %></td>
        <td><%= todolist.deadline %></td>
        <td><%= link_to '詳細', todolist %></td>
        <td><%= link_to '編集', edit_todolist_path(todolist) %></td>
        <td><%= link_to '削除', todolist, method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</CENTER>

<br>

<%= link_to 'HOME', top_index_path %> |
<%= link_to '新規作成', new_todolist_path %>

</body>

app/views/todolists/new.html.erb
<h1>TODO新規登録</h1>

<%= render 'form', todolist: @todolist %>

<%= link_to 'HOME', top_index_path %> |
<%= link_to '戻る', todolists_path %>

app/views/todolists/show.html.erb
<p id="notice"><%= notice %></p>

<!DOCTYPE html>
<html lang='ja'>
<head>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width'>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.0/css/bootstrap.min.css"></link>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.10/angular.min.js"></script>

<link rel="stylesheet" type="text/css" href="1026.css">

</head>
<body>

<p>
  <strong>登録日:</strong>
  <%= @todolist.today %>
</p>

<p>
  <strong>TODO:</strong>
  <%= @todolist.todo %>
</p>

<p>
  <strong>メモ:</strong>
  <%= @todolist.memo %>
</p>

<p>
  <strong>〆切:</strong>
  <%= @todolist.deadline %>
</p>

<%= link_to '編集', edit_todolist_path(@todolist) %> |
<%= link_to '戻る', todolists_path %>


</body>

app/views/top/index.html.erb
<!DOCTYPE html>
<html lang='ja'>
<head>
<meta charset='utf-8'>
<meta name='viewport' content='width=device-width'>

<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.0/css/bootstrap.min.css"></link>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.2.10/angular.min.js"></script>

<link rel="stylesheet" type="text/css" href="1026.css">

</head>

<body>

<h1>TODOリスト<br>管理システム</h1>
<%= link_to "新規作成", new_todolist_path %>
<hr>
<div class="count">
<h1>現在の課題数</h1>
<h2><%= @todolists.count %></h2>
</div>
<hr>
<%= link_to "新規作成", new_todolist_path %>

</body>